import { A, Fight, R, EventTemplate } from './eventTypes';

// ==========================================================
// 擴充事件：條件事件、連鎖事件、稀有 / 傳說事件、季節事件、末日前兆
// ==========================================================

// ---------- 共用副行動 ----------

const SUB_DRINK = A('x_drink', '順路找水', '花點時間尋找乾淨的水源', 'int', 9, [3, 0],
  R('你找到一處清澈的小水窪。', 0, 0, 18), R('附近的水都混濁不堪。'));

const SUB_REST = A('x_rest', '找地方休養', '安靜地休息，恢復傷勢', 'int', 6, [2, 2],
  R('你好好睡了一覺，傷口舒緩了許多。', 12), R('周遭太吵，沒能好好休息。', 4), { tags: ['rest'] });

const SUB_FORAGE = A('x_forage', '順手覓食', '沿途撿拾能吃的東西', 'int', 9, [3, 2],
  R('你找到了一些可以果腹的東西。', 0, 14, 3), R('一無所獲。'));

const SUB_STUDY = A('x_study', '觀察環境', '仔細觀察周圍的一草一木', 'int', 10, [2, 2],
  R('你注意到了一些以前沒發現的細節。（古生物知識 +1）', 0, 0, 0, { knowledge: 1 }),
  R('你看了半天，什麼也沒看出來。'), { tags: ['study'] });

const SUB_SCOUT = A('x_scout', '偵察四周', '爬上高處觀察地形', 'agi', 10, [4, 3],
  R('你掌握了附近的地形，找到一條安全的小路。', 3, 5, 5), R('視野被樹林擋住了。'));

// ---------- 事件 ----------

export const EXTRA_EVENTS: EventTemplate[] = [
  // ===== 連鎖：神秘的蛋 =====
  {
    id: 'mystery_egg',
    stages: ['juvenile', 'adolescent'],
    rarity: 'rare',
    weight: 0.7,
    condition: s => !s.flags.adopted_egg,
    narratives: [
      '你在一堆倒塌的蕨類下發現了一顆被遺棄的蛋，蛋殼摸起來還是溫的。',
      '暴風雨過後，一顆不知從哪個巢穴滾落的蛋停在你腳邊，輕輕晃了一下。',
    ],
    fact: '恐龍蛋殼上有細小的氣孔讓胚胎呼吸。部分恐龍（例如竊蛋龍類）會像鳥類一樣坐在巢上孵蛋。',
    mainActions: [
      A('incubate_egg', '把蛋藏起來孵化', '用落葉和體溫保護它，看看會孵出什麼', 'int', 10, [8, 5],
        R('你把蛋藏在溫暖的落葉堆裡，每天守著它。某天夜裡，蛋殼裡傳來了微弱的敲擊聲……（連鎖事件）', 0, -5, 0, { setFlags: ['adopted_egg'] }),
        R('你盡力了，但那顆蛋還是一點一點地涼了下去。', 0, -5, 0)),
      A('eat_egg', '吃掉它', '營養豐富，不吃白不吃', 'str', 6, [2, 2],
        R('營養豐富的一餐。', 0, 25, 5), R('蛋殼比你想的還硬，咬了半天只舔到一點蛋液。', 0, 8, 2)),
      A('leave_egg', '把蛋推回灌木叢', '也許牠的母親會回來找', 'cha', 5, [1, 1],
        R('你把蛋推回灌木叢裡。遠處傳來一聲焦急的呼喚——牠的母親回來了。你覺得心裡暖暖的。', 0, 0, 0, { statChanges: { cha: 1 } }),
        R('你把蛋推回灌木叢裡，然後離開了。')),
    ],
    subActions: [SUB_FORAGE, SUB_STUDY],
  },
  {
    id: 'egg_hatch',
    stages: ['juvenile', 'adolescent', 'adult'],
    rarity: 'chain',
    weight: 6,
    condition: s => !!s.flags.adopted_egg && s.year >= s.flags.adopted_egg + 2 && !s.flags.egg_hatched,
    narratives: ['你守護了好久的那顆蛋，終於在一個霧濛濛的清晨裂開了！'],
    mainActions: [
      A('welcome_hatchling', '迎接新生命', '輕輕舔去牠身上的蛋殼碎片', 'cha', 6, [5, 3],
        R('一隻濕漉漉的幼崽搖搖晃晃地爬出來，把你當成了媽媽。你的族群多了一名成員！', 0, 0, 0, { packChange: 1, setFlags: ['egg_hatched'] }),
        R('幼崽非常虛弱，你不眠不休地照顧，牠終於活了下來，成為你族群的一員。', -5, -10, 0, { packChange: 1, setFlags: ['egg_hatched'] })),
      A('teach_hatchling', '立刻教牠求生技巧', '叼著牠去認識這個世界', 'int', 10, [8, 5],
        R('小傢伙學得飛快！牠成為了你族群中最機靈的成員。', 0, 0, 0, { packChange: 1, setFlags: ['egg_hatched'], statChanges: { int: 1 } }),
        R('牠還太小，學不太會。不過牠還是寸步不離地跟著你。', 0, -5, 0, { packChange: 1, setFlags: ['egg_hatched'] })),
      A('inspect_hatchling', '仔細端詳牠', '這隻幼崽……長得好像哪裡不太對？', 'int', 13, [2, 2],
        R('等等……這不是恐龍，是一隻小翼龍！牠在你身邊長大，某天振翅飛向了天空。你總覺得，牠還會回來。', 0, 0, 0, { setFlags: ['egg_hatched', 'ptero_friend'], knowledge: 1 }),
        R('你看不出什麼所以然。牠跟著你，成了族群的一員。', 0, 0, 0, { packChange: 1, setFlags: ['egg_hatched'] })),
    ],
    subActions: [SUB_FORAGE, SUB_REST],
  },

  // ===== 彩蛋：小毛球 =====
  {
    id: 'little_furball',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 0.8,
    condition: s => !s.flags.spared_mammal && !s.flags.furball_met,
    tags: ['night'],
    narratives: ['一隻毛茸茸、老鼠大小的小動物正在偷吃你藏起來的食物。牠停下動作，用黑豆般的眼睛瞪著你。'],
    fact: '白堊紀末期的哺乳動物大多只有老鼠到貓的大小。恐龍滅絕後，牠們迎來了大爆發——其中一支，最終演化出了靈長類。',
    mainActions: [
      A('eat_furball', '一口吞掉牠', '送上門的點心', 'agi', 10, [2, 2],
        R('小小的一口，塞牙縫都不夠。', 0, 6, 0, { setFlags: ['furball_met'] }),
        R('牠一溜煙鑽進了地洞，消失得無影無蹤。', 0, 0, 0, { setFlags: ['furball_met'] })),
      A('spare_furball', '放牠一馬', '這麼小一隻，算了吧', 'cha', 3, [0, 0],
        R('小傢伙愣了一下，叼著一顆種子跑開前，回頭看了你一眼——那眼神，奇怪地像是在道謝。', 0, -3, 0, { setFlags: ['spared_mammal'] }),
        R('小傢伙愣了一下，叼著一顆種子跑開前，回頭看了你一眼——那眼神，奇怪地像是在道謝。', 0, -3, 0, { setFlags: ['spared_mammal'] })),
      A('chase_off', '把牠趕走', '保護你的存糧', 'str', 6, [3, 2],
        R('牠逃走了，你的食物保住了。', 0, 8, 0, { setFlags: ['furball_met'] }),
        R('牠逃走時還順手叼走了你最好的一塊肉。', 0, -3, 0, { setFlags: ['furball_met'] })),
    ],
    subActions: [SUB_DRINK, SUB_REST],
  },

  // ===== 救助流浪者（不需伴侶也能擴展族群） =====
  {
    id: 'wounded_stranger',
    stages: ['adolescent', 'adult'],
    weight: 0.9,
    condition: s => s.packSize < 6,
    narratives: [
      '路邊倒著一隻受傷的同類，腿上有深深的咬痕。牠虛弱地望著你。',
      '一隻被族群拋棄的年輕恐龍在寒風中發抖，看起來好幾天沒吃東西了。',
    ],
    mainActions: [
      A('nurse_stranger', '照顧牠恢復', '分享食物、替牠守夜', 'int', 11, [12, 8],
        R('幾天後，牠恢復了力氣，決定跟隨你——你的族群有了新成員！', 0, -5, 0, { packChange: 1 }),
        R('你盡了全力，但牠傷得太重了……你在牠身旁守到了最後。', 0, -5, 0)),
      A('recruit_stranger', '以氣勢收服牠', '讓牠知道跟著你才有活路', 'cha', 13, [5, 5],
        R('牠被你的氣度折服，低下頭成為你的追隨者。', 0, 0, 0, { packChange: 1, statChanges: { cha: 1 } }),
        R('牠不信任你，拖著傷腿消失在林間。')),
      A('rob_stranger', '搶走牠身邊的食物', '弱肉強食，天經地義', 'str', 8, [4, 3],
        R('你搶走了牠僅剩的食物。這種事，做多了會被記住的。', 0, 20, 0, { statChanges: { cha: -1 } }),
        R('牠拚死反抗，咬了你一口。', -8, 0, 0)),
    ],
    subActions: [SUB_REST, SUB_FORAGE],
  },

  // ===== 掠食者 =====
  {
    id: 'quetzal_stalker',
    stages: ['juvenile', 'adolescent'],
    weight: 0.9,
    narratives: [
      '一個比樹還高的影子擋住了陽光——一隻巨型翼龍收起翅膀，用四肢在地上大步朝你走來！',
      '河岸邊，一隻高得像樹的翼龍正低頭啄食。牠轉過頭，長長的喙對準了你。',
    ],
    fact: '風神翼龍（Quetzalcoatlus）翼展可達 10 公尺以上，站立時高度接近長頸鹿。許多學者認為牠們常在地面上行走，捕捉小型動物。',
    mainActions: [
      Fight('fight_ptero', '正面迎戰', '跳起來咬住牠的翅膀！', 'ptero', 11, [10, 8],
        R('你咬住了牠脆弱的翼膜，巨獸吃痛飛走了，還留下了剛捕到的獵物。', 0, 25, 0, { statChanges: { str: 1 } }),
        R('牠的長喙狠狠啄中了你。', -15, 0, 0)),
      A('hide_bush', '鑽進荊棘叢', '牠的長喙伸不進去', 'agi', 10, [5, 3],
        R('牠的長喙在荊棘外戳了半天，悻悻然地飛走了。'), R('你慢了一步，被啄傷了尾巴。', -15, 0, 0), { tags: ['flee'] }),
      A('play_dead', '裝死', '一動也不動', 'int', 12, [1, 1],
        R('牠用喙戳了戳你，失去了興趣。你學到了一課。（古生物知識 +1）', 0, 0, 0, { knowledge: 1 }),
        R('牠才不吃這一套！', -18, 0, 0)),
    ],
    subActions: [SUB_DRINK, SUB_STUDY],
  },
  {
    id: 'croc_river',
    stages: ['adolescent', 'adult'],
    weight: 0.9,
    narratives: [
      '你低頭在渾濁的河邊喝水，水面突然隆起——一對眼睛正盯著你。',
      '乾旱讓所有動物都擠在僅存的河灣飲水，而水裡潛伏著巨大的陰影。',
    ],
    fact: '恐鱷（Deinosuchus）是白堊紀晚期的巨型鱷類，體長可達 10 公尺以上，咬痕化石顯示牠們會攻擊恐龍。',
    mainActions: [
      Fight('fight_croc', '與巨鱷搏鬥', '在岸邊正面對決', 'croc', 13, [12, 5],
        R('你在岸邊擊退了巨鱷，大口暢飲，還叼走了牠藏在水草間的魚。', 0, 30, 30),
        R('巨鱷把你拖進了水裡翻滾，你拚命才掙脫。', -20, 0, 10)),
      A('drink_fast', '喝一口就跑', '速戰速決', 'agi', 11, [3, 0],
        R('你在巨鱷撲上來前跳開了，嘴裡還含著滿滿的水。', 0, 0, 25),
        R('你被尾巴掃中了。', -15, 0, 10), { tags: ['flee'] }),
      A('distant_water', '繞遠路找別的水源', '安全第一', 'int', 10, [8, 5],
        R('你找到了一處安全的小溪。', 0, 0, 20), R('走了很遠也沒找到水。', -5, 0, -5)),
      A('pack_decoy', '族群佯攻引開巨鱷', '讓族人在上游拍打水面', 'cha', 11, [5, 3],
        R('巨鱷被上游的聲響引開了，大家暢快地喝了個夠！族群的默契更好了。', 0, 0, 35, { statChanges: { cha: 1 } }),
        R('巨鱷沒有上當，還咬住了一名族人……', 0, 0, 10, { packChange: -1 }),
        { requires: { minPack: 2 } }),
    ],
    subActions: [SUB_REST, SUB_SCOUT],
  },
  {
    id: 'ankylo_standoff',
    stages: ['adolescent', 'adult'],
    weight: 0.7,
    narratives: ['一隻甲龍霸佔了唯一的泉眼，牠的尾錘在空中緩緩搖擺，警告任何靠近的生物。'],
    fact: '甲龍的尾錘由融合的骨板構成，研究估計揮擊力量足以擊碎大型掠食者的骨頭。',
    mainActions: [
      Fight('fight_ankylo', '挑戰甲龍', '想喝水？先打贏再說', 'ankylo', 14, [12, 8],
        R('你找到了牠裝甲的弱點——柔軟的腹部。甲龍落荒而逃，泉水歸你了！', 0, 15, 30, { statChanges: { str: 1 } }),
        R('尾錘正中你的側腹，你痛得站不起來。', -22, 0, 0)),
      A('share_spring', '低頭示好，請求分享', '甲龍只吃植物，也許不會趕你', 'cha', 12, [3, 3],
        R('甲龍哼了一聲，默許了你的存在。你們一起喝了水。', 0, 0, 25),
        R('甲龍一尾巴甩了過來！', -12, 0, 0)),
      A('wait_turn', '耐心等牠離開', '甲龍總會走的', 'int', 9, [6, 6],
        R('傍晚時分，甲龍慢吞吞地離開了。', 0, 0, 18), R('你等到天黑，牠還是不走。', 0, -5, -8)),
    ],
    subActions: [SUB_FORAGE, SUB_STUDY],
  },

  // ===== 環境與奇遇 =====
  {
    id: 'cretaceous_bees',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 0.6,
    narratives: ['一棵枯樹的樹洞裡傳來嗡嗡聲，空氣中飄著甜甜的氣味。'],
    fact: '已知最古老的蜜蜂化石之一「Cretotrigona prisca」保存在白堊紀晚期的琥珀裡——恐龍的時代，已經有會採蜜的蜂了！',
    mainActions: [
      A('raid_hive', '硬搶蜂巢', '皮厚不怕螫', 'str', 11, [6, 4],
        R('你扒開樹洞，大口吞下甜滋滋的蜂巢。被螫了幾下，但值得！', -3, 25, 5),
        R('蜂群傾巢而出，你被螫得滿頭包！', -12, 0, 0)),
      A('sneak_honey', '趁蜂群外出時偷舔', '輕手輕腳', 'agi', 12, [4, 3],
        R('你偷到了好幾口蜂蜜，全身而退。', 0, 18, 3), R('被發現了！', -8, 0, 0)),
      A('observe_bees', '觀察蜂群飛去哪裡', '跟著蜜蜂一定有花', 'int', 8, [3, 3],
        R('你跟著蜂群找到了一片開滿花的灌木叢，附近果實纍纍。（古生物知識 +1）', 0, 15, 5, { knowledge: 1 }),
        R('蜜蜂飛太快了，你跟丟了。'), { tags: ['study'] }),
    ],
    subActions: [SUB_DRINK, SUB_REST],
  },
  {
    id: 'amber_mosquito',
    stages: ['juvenile', 'adolescent', 'adult'],
    rarity: 'rare',
    weight: 0.35,
    condition: s => !s.flags.amber_seen,
    narratives: ['陽光下，一塊金黃色的樹脂閃閃發亮。你湊近一看，裡面困著一隻蚊子。'],
    fact: '琥珀能完美保存昆蟲的外形上億年。但研究估計 DNA 的半衰期約 521 年，要保存 6600 萬年幾乎不可能——所以《侏羅紀公園》的做法在現實中行不通。',
    mainActions: [
      A('stare_amber', '盯著它看', '這隻蚊子……好像在訴說什麼', 'int', 9, [2, 2],
        R('你盯著琥珀看了整整一個下午。莫名地，你覺得自己看懂了某種關於「時間」的東西。', 0, 0, 0, { traitGainId: 'amber_wisdom', knowledge: 2, setFlags: ['amber_seen'] }),
        R('你看著看著就睡著了。', 5, 0, 0, { knowledge: 1, setFlags: ['amber_seen'] }), { tags: ['study'] }),
      A('lick_amber', '舔一口', '看起來很像蜂蜜', 'str', 5, [1, 1],
        R('……黏黏的。一點都不好吃。你到底在期待什麼？', 0, -2, 0, { setFlags: ['amber_seen'] }),
        R('……黏黏的。一點都不好吃。你到底在期待什麼？', 0, -2, 0, { setFlags: ['amber_seen'] })),
      A('bury_amber', '把它埋起來', '總覺得應該好好收著', 'cha', 5, [2, 1],
        R('你把琥珀埋進土裡。6600 萬年後，也許會有某種兩腳生物把它挖出來。', 0, 0, 0, { setFlags: ['amber_seen', 'buried_amber'] }),
        R('你把琥珀埋進土裡。6600 萬年後，也許會有某種兩腳生物把它挖出來。', 0, 0, 0, { setFlags: ['amber_seen', 'buried_amber'] })),
    ],
    subActions: [SUB_FORAGE, SUB_DRINK],
  },
  {
    id: 'ancient_fossil',
    stages: ['adolescent', 'adult'],
    rarity: 'rare',
    weight: 0.3,
    narratives: ['河床上一塊石頭印著漂亮的螺旋紋路。那是比你古老得多的生物——菊石的化石。'],
    fact: '菊石在地球海洋中繁盛了超過 3 億年，最終也在白堊紀末大滅絕中與非鳥恐龍一同消失。',
    mainActions: [
      A('ponder_fossil', '凝視這塊化石', '牠曾經也是活生生的', 'int', 8, [2, 2],
        R('你凝視著這塊比你古老千萬年的石頭……你突然意識到，總有一天，你也會變成這樣。（古生物知識 +2）', 0, 0, 0, { knowledge: 2, statChanges: { int: 1 } }),
        R('看起來就是塊石頭。', 0, 0, 0, { knowledge: 1 }), { tags: ['study'] }),
      A('sharpen_on_fossil', '拿來磨爪子', '硬度剛剛好', 'str', 7, [3, 2],
        R('你的爪子變得更鋒利了。', 0, 0, 0, { statChanges: { str: 1 } }), R('化石碎掉了。')),
      A('drink_river_fossil', '順便在河床喝水', '別想太多', 'int', 5, [1, 0],
        R('河水清涼。', 0, 0, 20), R('水有點混濁。', 0, 0, 8)),
    ],
    subActions: [SUB_FORAGE, SUB_SCOUT],
  },
  {
    id: 'stampede',
    stages: ['adolescent', 'adult'],
    weight: 0.8,
    narratives: ['大地劇烈震動——一大群受驚的角龍正朝你的方向狂奔而來！'],
    fact: '北美曾發現大量角龍集體埋藏的「骨床」，顯示部分角龍可能成群生活或遷徙。',
    mainActions: [
      A('dodge_stampede', '往側面閃開', '離開獸群的路線', 'agi', 11, [5, 5],
        R('你在最後一刻跳開，獸群從你身邊轟隆而過。'), R('你被擦撞了一下，滾了好幾圈。', -22, 0, 0), { tags: ['flee'] }),
      A('run_with_herd', '順著獸群一起跑', '混進去就不會被踩', 'agi', 13, [8, 8],
        R('你混在獸群中奔跑，順勢跑到了一片沒被發現過的綠地。', 0, 18, 12),
        R('你被後面的角龍撞倒了。', -15, 0, 0)),
      A('shield_rock', '躲到巨石後面', '讓岩石替你擋', 'int', 10, [2, 2],
        R('獸群在巨石前分流，你毫髮無傷。還撿到了被踩死的小型獵物。', 0, 10, 0),
        R('岩石不夠大……', -15, 0, 0)),
    ],
    subActions: [SUB_REST, SUB_STUDY],
  },
  {
    id: 'night_storm',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 0.8,
    tags: ['night'],
    narratives: ['深夜，一場雷暴突然襲來。閃電照亮了樹林，你看見黑暗中有東西在移動……'],
    fact: '雷擊是自然野火的主要成因之一。白堊紀地層中常能找到大量木炭，顯示當時野火相當頻繁。',
    mainActions: [
      A('seek_shelter_night', '摸黑找避雨處', '在黑暗中尋找岩壁或洞穴', 'int', 10, [3, 2],
        R('你在閃電照亮的一瞬間看見一處岩壁，安穩地度過了一夜。', 5, 0, 5),
        R('你在黑暗中撞上了樹幹。', -8, 0, 5), { tags: ['night'] }),
      A('investigate_movement', '去看看那是什麼', '好奇心會殺死恐龍嗎？', 'agi', 12, [5, 3],
        R('是一隻被閃電嚇呆的小型獵物！送上門的晚餐。', 0, 20, 0),
        R('是一隻脾氣很差的甲龍。你被尾巴掃了一下。', -12, 0, 0), { tags: ['night'] }),
      A('stand_watch', '整夜警戒', '不讓任何東西靠近', 'cha', 10, [4, 3],
        R('你整夜守著，平安度過。天亮時你發現有東西曾在附近徘徊，最後被你的氣勢嚇退了。', 0, 0, 0, { statChanges: { cha: 1 } }),
        R('你撐到一半就睡著了，醒來時存糧少了一些。', 0, -8, 0)),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },
  {
    id: 'sinkhole_cave',
    stages: ['adolescent', 'adult'],
    weight: 0.7,
    condition: s => !s.flags.knows_cave,
    narratives: ['地面忽然塌陷，露出一個深不見底的天坑。冷風從底下吹上來，還伴隨著潺潺水聲。'],
    fact: '洞穴與地下空間的溫度全年穩定。在大災難中，地下往往是最後的避難所。',
    mainActions: [
      A('explore_sinkhole', '小心探索天坑', '找一條能下去的路', 'int', 12, [5, 3],
        R('天坑底部是一整個地下洞穴系統，還有清澈的地下河！你牢牢記住了這個秘密據點。', 0, 0, 25, { setFlags: ['knows_cave'] }),
        R('你滑了下去，摔得不輕，只好狼狽地爬上來。', -12, 0, 0)),
      A('climb_down', '直接爬下去', '靠爪子和力氣', 'str', 12, [8, 5],
        R('你硬是爬到了底部，發現了一個寬敞的洞穴。這裡能擋住世界上任何風暴。', 0, 0, 15, { setFlags: ['knows_cave'] }),
        R('岩壁崩落，你摔了下去。', -15, 0, 0)),
      A('mark_sinkhole', '在旁邊留下氣味記號', '以後再來', 'int', 6, [1, 1],
        R('你標記了位置。（古生物知識 +1）', 0, 0, 0, { knowledge: 1 }), R('雨水很快沖掉了氣味。')),
    ],
    subActions: [SUB_DRINK, SUB_SCOUT],
  },
  {
    id: 'fern_meadow',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 1,
    condition: s => s.species?.diet !== 'carnivore',
    narratives: ['一片翠綠的蕨類平原在眼前展開，遠處的灌木開滿了小花。'],
    fact: '白堊紀末期雖然已經有草，但還沒有大片草原。恐龍時代的地面大多被蕨類、蘇鐵、針葉樹與新興的開花植物覆蓋。',
    mainActions: [
      A('graze_meadow', '大快朵頤', '吃到飽為止', 'int', 8, [4, 3],
        R('鮮嫩的蕨葉讓你吃得心滿意足。', 0, 30, 5), R('蕨葉有點老，只吃了個半飽。', 0, 12, 0)),
      A('graze_flowers', '專挑花朵吃', '聽說花比較營養', 'agi', 10, [4, 3],
        R('你嚼著花朵，身上帶著淡淡的花香。', 0, 22, 5, { statChanges: { cha: 1 } }), R('花裡有蟲，你被咬了一口。', -3, 8, 0)),
      A('join_herd', '接近其他植食恐龍群', '結識新夥伴', 'cha', 12, [5, 5],
        R('一隻年輕的同類離開了原本的群體，選擇跟隨你。', 0, 10, 0, { packChange: 1 }),
        R('牠們把你當成外人，不理不睬。', 0, 5, 0)),
    ],
    subActions: [SUB_DRINK, SUB_REST],
  },
  {
    id: 'titan_carcass',
    stages: ['adolescent', 'adult'],
    weight: 1,
    condition: s => s.species?.diet !== 'herbivore',
    narratives: ['一具如山丘般巨大的阿拉莫龍屍體倒在平原上，腐肉的氣味方圓數公里都聞得到。各路掠食者正在聚集。'],
    fact: '阿拉莫龍（Alamosaurus）是白堊紀末期北美的巨型泰坦巨龍，體長可達 26 公尺以上，是北美最後的蜥腳類之一。',
    mainActions: [
      Fight('claim_carcass', '霸佔屍體', '趕走其他搶食者', 'raptor', 12, [10, 8],
        R('你趕走了馳龍群，獨佔這座肉山！', 0, 45, 5),
        R('馳龍群圍攻你，你被迫放棄了。', -18, 5, 0)),
      A('sneak_bites', '趁亂偷咬幾口', '混水摸魚', 'agi', 10, [4, 3],
        R('你撕下了一大塊肉就跑。', 0, 25, 0), R('被一隻大傢伙撞開了。', -10, 5, 0)),
      A('pack_feast', '帶族群一起大快朵頤', '輪流警戒、輪流進食', 'cha', 11, [6, 4],
        R('族人們輪流警戒、輪流進食，一場完美的盛宴！', 0, 40, 5, { statChanges: { cha: 1 } }),
        R('族群亂成一團，只吃到一點。', 0, 15, 0), { requires: { minPack: 2 } }),
    ],
    subActions: [SUB_DRINK, SUB_REST],
  },
  {
    id: 'elder_wisdom',
    stages: ['adolescent'],
    weight: 0.7,
    narratives: ['一隻年老的恐龍在河邊休息，牠的鱗片斑駁，眼神卻異常清澈。'],
    mainActions: [
      A('learn_elder', '向牠學習', '安靜地聽', 'int', 10, [3, 3],
        R('牠教你辨認天象、預測洪水，還有——大難來臨時，要往地下或水裡躲。（古生物知識 +2）', 0, 0, 0, { knowledge: 2, statChanges: { int: 2 } }),
        R('你聽得似懂非懂。（古生物知識 +1）', 0, 0, 0, { knowledge: 1 }), { tags: ['study'] }),
      A('share_elder', '分食物給牠', '尊重長者', 'cha', 7, [8, 3],
        R('老恐龍感激地點點頭，告訴你一處秘密的洞穴位置。', 0, -5, 0, { setFlags: ['knows_cave'], statChanges: { cha: 1 } }),
        R('老恐龍謝過你，閉上眼睛睡著了。', 0, -5, 0)),
      A('spar_elder', '向牠挑戰', '看看老傢伙還剩幾分實力', 'str', 12, [6, 5],
        R('牠用最省力的方式把你壓在地上。你學會了技巧比蠻力重要。', 0, 0, 0, { statChanges: { str: 1, agi: 1 } }),
        R('牠一尾巴把你掃倒了。', -8, 0, 0)),
    ],
    subActions: [SUB_DRINK, SUB_FORAGE],
  },

  // ===== 手足（連鎖） =====
  {
    id: 'sibling_bond',
    stages: ['juvenile'],
    weight: 1,
    condition: s => !s.flags.sibling_bond && !s.flags.sibling_rival,
    narratives: ['你和同窩的兄弟姊妹擠在一起取暖。其中最瘦小的那隻總是搶不到食物。'],
    mainActions: [
      A('share_sibling', '把食物分給牠', '你們是一家人', 'cha', 7, [6, 2],
        R('你把食物讓給了牠。牠依偎著你，從此形影不離。（未來可能發生連鎖事件）', 0, -6, 0, { setFlags: ['sibling_bond'] }),
        R('牠吃了，但似乎更依賴母親。', 0, -6, 0)),
      A('compete_sibling', '搶最大的那份', '弱肉強食', 'str', 9, [4, 2],
        R('你搶到了最大的一份，長得比誰都快。', 0, 18, 0, { statChanges: { str: 1 }, setFlags: ['sibling_rival'] }),
        R('大家一擁而上，你被踩在最底下。', -5, 5, 0)),
      A('play_sibling', '和牠們追逐嬉戲', '在玩耍中長大', 'agi', 8, [5, 3],
        R('你們在蕨叢間追逐，你的腳步越來越靈活。', 0, 0, 0, { statChanges: { agi: 1 } }),
        R('你跌了個狗吃屎。', -3, 0, 0)),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },
  {
    id: 'sibling_reunion',
    stages: ['adolescent', 'adult'],
    rarity: 'chain',
    weight: 5,
    condition: s => !!s.flags.sibling_bond && s.year >= 8 && !s.flags.sibling_joined,
    narratives: ['一個熟悉的身影從遠方跑來——是當年那隻最瘦小的兄弟姊妹！牠已經長得和你一樣大了。'],
    mainActions: [
      A('welcome_sibling', '熱情相迎', '好久不見！', 'cha', 4, [2, 2],
        R('你們蹭著彼此的脖子。牠決定留下來，成為你族群的一員。', 0, 0, 0, { packChange: 1, setFlags: ['sibling_joined'] }),
        R('你們蹭著彼此的脖子。牠決定留下來，成為你族群的一員。', 0, 0, 0, { packChange: 1, setFlags: ['sibling_joined'] })),
      A('hunt_sibling', '一起去狩獵', '像小時候一樣', 'str', 10, [8, 5],
        R('你們默契十足地捕到一頓大餐。牠決定留下來了！', 0, 25, 5, { packChange: 1, setFlags: ['sibling_joined'] }),
        R('雖然空手而歸，牠還是決定留下來。', 0, 0, 0, { packChange: 1, setFlags: ['sibling_joined'] })),
    ],
    subActions: [SUB_REST, SUB_FORAGE],
  },

  // ===== 成年：族群與伴侶 =====
  {
    id: 'mate_in_danger',
    stages: ['adult'],
    weight: 0.7,
    condition: s => s.hasMate,
    narratives: [
      '你的伴侶在河邊飲水時，一隻暴龍悄悄從林中逼近！',
      '尖銳的呼救聲劃破寧靜——是你的伴侶！一隻暴龍正把牠逼到了懸崖邊。',
    ],
    mainActions: [
      Fight('defend_mate', '衝上去保護伴侶', '用你的身體擋在前面', 'tyrant', 14, [12, 8],
        R('你擋在伴侶身前，把暴龍趕走了！伴侶用頭輕輕蹭著你的傷口。', 0, 10, 0, { statChanges: { cha: 1 } }),
        R('你受了重傷，而你的伴侶……沒能逃過這一劫。', -10, 0, 0, { mateLoss: true })),
      A('distract_predator', '引開掠食者', '朝反方向大吼，讓牠追你', 'agi', 13, [10, 8],
        R('你大吼一聲把暴龍引向反方向，在林間甩掉了牠。伴侶安全了。', 0, 0, 0, { statChanges: { agi: 1 } }),
        R('暴龍沒有被引開……你只能眼睜睜看著伴侶倒下。', -15, 0, 0, { mateLoss: true }), { tags: ['flee'] }),
      A('pack_mob', '召集族群圍攻', '一起上！', 'cha', 12, [8, 5],
        R('族人們一擁而上，暴龍權衡了一下，轉身離開。', 0, 0, 0),
        R('混戰中，一名族人為了保護伴侶犧牲了。', -5, 0, 0, { packChange: -1 }), { requires: { minPack: 2 } }),
    ],
    subActions: [SUB_REST, SUB_SCOUT],
  },
  {
    id: 'rival_wanderer',
    stages: ['adolescent', 'adult'],
    weight: 0.7,
    condition: s => !s.flags.ally_rival && !s.flags.rival_beaten,
    narratives: ['一隻滿身傷疤的流浪同類闖入你的領地，用低吼向你下了戰帖。'],
    mainActions: [
      Fight('duel_rival', '接受決鬥', '讓牠見識你的實力', 'rival', 13, [10, 8],
        R('你贏了。牠倒在地上喘息，眼神中已不再有敵意。', 0, 12, 0, { statChanges: { str: 1 }, setFlags: ['rival_beaten'] }),
        R('牠比你想的更強。', -15, 0, 0)),
      A('befriend_rival', '以禮相待，邀牠同行', '不打不相識', 'cha', 13, [6, 5],
        R('你們並肩走了一段路。臨別時，牠用鼻子碰了碰你——這份情誼，牠會記住的。（末日時或許會回報）', 0, 0, 0, { setFlags: ['ally_rival'] }),
        R('牠趁你不備咬了你一口，逃之夭夭。', -10, 0, 0)),
      A('avoid_rival', '避開牠', '不必要的戰鬥', 'agi', 9, [4, 3],
        R('你悄悄換了個地方棲息。'), R('牠追上來咬了你一口。', -8, 0, 0), { tags: ['flee'] }),
    ],
    subActions: [SUB_STUDY, SUB_REST],
  },
  {
    id: 'lost_juvenile',
    stages: ['adult'],
    weight: 0.7,
    condition: s => s.packSize >= 2,
    narratives: ['清點族群時，你發現一隻幼崽不見了！遠方隱約傳來微弱的叫聲。'],
    mainActions: [
      A('search_juvenile', '親自循聲搜尋', '一個都不能少', 'int', 11, [8, 6],
        R('你循著叫聲找到了卡在岩縫裡的幼崽，把牠救了出來。族群對你更加信賴。', 0, 0, 0, { statChanges: { cha: 1 } }),
        R('你找了一整天，只找到一些凌亂的腳印……', 0, 0, 0, { packChange: -1 })),
      A('send_scouts', '派族人分頭搜索', '分工合作', 'cha', 11, [4, 4],
        R('族人們很快就帶著幼崽回來了。', 0, 0, 0), R('天黑了，搜索隊只能無功而返。', 0, 0, 0, { packChange: -1 }),
        { requires: { minPack: 3 } }),
      A('abandon_search', '放棄搜索', '不能為了一隻幼崽冒全族的險', 'str', 3, [0, 0],
        R('這是領袖的決定。族群沉默地繼續前進。', 0, 0, 0, { packChange: -1 }),
        R('這是領袖的決定。族群沉默地繼續前進。', 0, 0, 0, { packChange: -1 })),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },
  {
    id: 'mammal_raid',
    stages: ['adult'],
    weight: 0.7,
    tags: ['night'],
    condition: s => s.hasMate || s.packSize >= 1,
    narratives: ['半夜，巢穴旁傳來細碎的聲響——一群體型像獾的哺乳動物正在偷吃你們的蛋！'],
    fact: '迪德爾菲獸（Didelphodon）是白堊紀末期北美的有袋類近親，咬合力在同體型哺乳類中名列前茅，可能以蛋、貝類與小動物為食。',
    mainActions: [
      A('guard_nest_night', '衝出去驅趕', '趁牠們還沒得手', 'int', 11, [5, 3],
        R('你及時驚醒，把牠們趕跑，還順手抓了一隻當宵夜。', 0, 10, 0),
        R('等你反應過來，一整窩蛋都被吃光了……', 0, -10, 0), { tags: ['night'] }),
      A('trap_raiders', '堵住洞口圍捕', '一網打盡', 'agi', 12, [6, 4],
        R('你堵住了牠們的退路，飽餐一頓。', 0, 18, 0), R('牠們從另一個洞口溜走了。', 0, -5, 0), { tags: ['night'] }),
      A('ignore_raiders', '翻個身繼續睡', '反正明年還能再生', 'int', 3, [0, 0],
        R('你繼續睡。早上起來，蛋少了幾顆。', 5, -8, 0), R('你繼續睡。早上起來，蛋少了幾顆。', 5, -8, 0), { tags: ['rest'] }),
    ],
    subActions: [SUB_REST, SUB_FORAGE],
  },

  // ===== 傳說事件 =====
  {
    id: 'albino_tyrant',
    stages: ['adult'],
    rarity: 'legendary',
    weight: 0.25,
    condition: s => !s.flags.albino_beaten && s.year >= 15,
    narratives: ['傳說中的白色巨獸出現了。牠的身上布滿數十年征戰的疤痕，所到之處，萬物噤聲。'],
    fact: '白化症在現代爬行動物與鳥類中都有紀錄，但這類個體通常很難在野外存活——能長大的，都是狠角色。',
    mainActions: [
      Fight('fight_albino', '挑戰白化暴君', '傳說，就是用來打破的', 'albino_tyrant', 16, [15, 10],
        R('不可思議！你擊敗了傳說！所有目睹這一戰的恐龍都將傳頌你的名字。（獲得傳說詞條「白色傳說」）', 0, 50, 0, { traitGainId: 'legend_hunter', setFlags: ['albino_beaten'] }),
        R('你見識到了傳說的力量。能活著離開已是奇蹟。', -20, 0, 0)),
      A('hide_albino', '屏息躲藏觀察', '看清楚傳說的樣子', 'int', 13, [2, 2],
        R('白色巨獸從你藏身的灌木旁走過。你記住了牠的每一個動作。（古生物知識 +2）', 0, 0, 0, { knowledge: 2 }),
        R('牠聞到了你！', -25, 0, 0)),
      A('flee_albino', '拔腿就跑', '留得青山在', 'agi', 12, [8, 8],
        R('你頭也不回地跑了好幾公里。'), R('牠只踏出三步就追上了你。', -20, 0, 0), { tags: ['flee'] }),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },

  // ===== 季節事件 =====
  {
    id: 'season_drought',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 2.5,
    condition: s => s.season === 'drought',
    narratives: ['大旱讓水塘縮成了一灘爛泥，所有動物都盯著最後那一點水。'],
    mainActions: [
      A('dig_mud_water', '往泥底下挖', '底下也許還有水', 'str', 11, [8, 3],
        R('你挖到了濕潤的地層，滲出的泥水救了你一命。', 0, 0, 25), R('挖到的全是乾土。', 0, 0, -5)),
      A('follow_birds', '跟著鳥群走', '鳥總是知道水在哪裡', 'int', 12, [5, 5],
        R('你跟著鳥群找到了隱密的泉水。（古生物知識 +1）', 0, 0, 30, { knowledge: 1 }), R('鳥飛得太遠了。', 0, 0, -5), { tags: ['study'] }),
      Fight('fight_for_water', '為水源而戰', '把其他動物趕走', 'raptor', 12, [10, 5],
        R('水源是你的了！', 0, 5, 35), R('你被趕走了。', -15, 0, 0)),
    ],
    subActions: [SUB_REST, SUB_FORAGE],
  },
  {
    id: 'season_cold',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 2.5,
    condition: s => s.season === 'cold',
    narratives: ['寒流來襲，清晨的地面結了一層薄霜。你的動作變得遲緩。'],
    fact: '大型恐龍體積大、散熱慢，能較穩定地維持體溫（稱為「巨溫性」）；小型恐龍則可能依靠羽毛保暖。',
    mainActions: [
      A('bask_sun', '找陽光曬太陽', '慢慢暖和起來', 'int', 8, [2, 2],
        R('陽光灑在身上，你重新活了過來。', 8), R('雲層太厚，一點陽光都沒有。', -3)),
      A('huddle_pack', '族群擠在一起取暖', '大家一起撐過去', 'cha', 7, [3, 3],
        R('族人們緊緊依偎在一起，彼此的體溫讓你們撐過了寒夜。', 12, 0, 0, { statChanges: { cha: 1 } }),
        R('有幾隻成員不願靠近，但你們還是撐過來了。', 4), { requires: { minPack: 1 } }),
      A('eat_more', '拚命進食儲存熱量', '吃越多越暖', 'str', 10, [5, 3],
        R('你大量進食，體內像燒著一團火。', 0, 28, 0), R('天寒地凍，找不到什麼吃的。', 0, 5, 0)),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },
  {
    id: 'season_bounty',
    stages: ['adolescent', 'adult'],
    weight: 2,
    condition: s => s.season === 'bounty',
    narratives: ['今年風調雨順，果實纍纍，獵物也肥美。整片森林都在歌唱。'],
    mainActions: [
      A('feast_bounty', '盡情享用', '難得的好年頭', 'int', 6, [4, 3],
        R('你吃得肚皮圓滾滾的。', 0, 30, 15), R('你吃太快，有點消化不良。', 0, 15, 8)),
      A('court_bounty', '趁好年頭求偶', '心情好，魅力也跟著上升', 'cha', 11, [10, 8],
        R('在這美好的季節裡，你找到了伴侶！', 0, 0, 0, { mateGain: true, traitRemove: 'grief' }),
        R('對方正忙著吃東西，沒空理你。'), { requires: { noMate: true, minYear: 13 } }),
      A('nest_bounty', '築一個舒適的大巢', '為下一代打算', 'int', 10, [8, 5],
        R('豐饒的季節裡，巢中一口氣孵出了新生命！', 0, 0, 0, { packChange: 1 }),
        R('巢還沒蓋好就下雨了。'), { requires: { mate: true } }),
    ],
    subActions: [SUB_REST, SUB_STUDY],
  },

  // ===== 末日前兆（為三重審判做準備） =====
  {
    id: 'meteor_shower',
    stages: ['adult'],
    weight: 1.2,
    tags: ['night'],
    condition: s => s.year >= 18 && !s.flags.omen_seen,
    narratives: ['夜空中劃過無數道流星，美得令人屏息。但有一顆星星……好像一夜比一夜更亮？'],
    fact: '終結恐龍時代的小行星直徑約 10 公里，以每秒約 20 公里的速度撞上今天墨西哥的猶加敦半島，留下直徑約 180 公里的希克蘇魯伯隕石坑。',
    mainActions: [
      A('watch_sky', '整夜觀察星空', '記下那顆星的位置', 'int', 10, [3, 2],
        R('你記下那顆星的位置。你的本能在尖叫：那東西正在靠近。（古生物知識 +2，末日時你會更早察覺）', 0, 0, 0, { setFlags: ['omen_seen'], knowledge: 2 }),
        R('你看著看著就睡著了。（古生物知識 +1）', 3, 0, 0, { knowledge: 1 }), { tags: ['night', 'study'] }),
      A('howl_sky', '對著星空咆哮', '不知道為什麼，就是想吼', 'cha', 8, [3, 3],
        R('什麼都沒發生。但你感覺超爽。', 0, 0, 0, { statChanges: { cha: 2 } }),
        R('一隻路過的甲龍用看白痴的眼神看著你。')),
      A('sleep_on', '繼續睡', '星星又不能吃', 'int', 3, [0, 0],
        R('你睡得很好。', 10), R('你睡得很好。', 10), { tags: ['rest'] }),
    ],
    subActions: [SUB_REST, SUB_FORAGE],
  },
  {
    id: 'deccan_prep',
    stages: ['adult'],
    weight: 2.2,
    condition: s => s.year >= 16 && (!s.flags.knows_cave || !s.flags.food_cache || !s.flags.near_lake),
    narratives: [
      '遠方火山的轟鳴越來越頻繁，天空總是灰濛濛的。動物們變得焦躁——你也感覺到，該為最壞的情況做準備了。',
      '空氣裡有股硫磺味，雨水嚐起來酸酸的。你的本能告訴你：大事即將發生。',
    ],
    fact: '德干暗色岩火山群位於今日印度，在白堊紀末期噴發出超過 100 萬立方公里的熔岩，並釋放大量二氧化碳與硫化物。',
    mainActions: [
      A('dig_deep_burrow', '挖掘深層地穴', '往地底挖，越深越好', 'str', 12, [10, 5],
        R('你挖出了一條深入地下的通道。泥土的溫度恆定，連外面的熱浪都傳不進來。（末日時可用）', 0, 0, 0, { setFlags: ['knows_cave'] }),
        R('土層太硬，你只挖出一個淺坑。', -5, 0, 0), { requires: { noFlag: 'knows_cave' } }),
      A('cache_food', '囤積並掩埋食物', '藏在只有你知道的地方', 'int', 11, [5, 3],
        R('你在好幾個地方埋下了肉乾與種子。（末日時可用）', 0, -8, 0, { setFlags: ['food_cache'] }),
        R('你埋的食物被偷挖走了。', 0, -10, 0), { requires: { noFlag: 'food_cache' } }),
      A('move_near_lake', '把棲地遷到大湖邊', '水是生命之源', 'agi', 11, [8, 5],
        R('你在一座深湖旁安頓下來，湖裡魚蝦成群。（末日時可用）', 0, 0, 20, { setFlags: ['near_lake'] }),
        R('遷徙途中迷了路。', -5, 0, -5), { requires: { noFlag: 'near_lake' } }),
      A('drill_pack', '訓練族群緊急撤離', '一聲令下，全員行動', 'cha', 12, [8, 5],
        R('族人們學會了聽你的號令一起行動、一起安靜。（末日時族群更易存活）', 0, 0, 0, { setFlags: ['pack_drilled'] }),
        R('族人們一團混亂。'), { requires: { minPack: 2, noFlag: 'pack_drilled' } }),
    ],
    subActions: [SUB_STUDY, SUB_FORAGE],
  },
  {
    id: 'last_days',
    stages: ['adult'],
    weight: 7,
    condition: s => s.year >= 23 && !s.flags.last_days,
    narratives: ['大地不停地微微震動。所有鳥類與翼龍都朝同一個方向飛去。末日的氣息已經濃得化不開。'],
    mainActions: [
      A('last_rally', '號召流浪者加入', '末日當前，團結才能活下去', 'cha', 12, [8, 5],
        R('消息傳開了：你是這片土地上最有準備的領袖。兩隻流浪恐龍前來投靠！', 0, 0, 0, { packChange: 2, setFlags: ['last_days'] }),
        R('沒有誰相信你的警告。', 0, 0, 0, { setFlags: ['last_days'] })),
      A('last_feast', '把自己吃到最飽', '接下來會很久沒東西吃', 'str', 9, [3, 3],
        R('你吃掉了能找到的一切。體內的脂肪就是你最後的保險。', 10, 35, 20, { setFlags: ['last_days'] }),
        R('周遭的動物都在搶食，你只吃到一點。', 0, 12, 8, { setFlags: ['last_days'] })),
      A('last_study', '觀察動物們逃往的方向', '牠們知道些什麼', 'int', 11, [3, 3],
        R('你發現小型動物都在往地洞與水邊躲。（古生物知識 +2）', 0, 0, 0, { knowledge: 2, setFlags: ['last_days'] }),
        R('動物們四散奔逃，看不出規律。', 0, 0, 0, { setFlags: ['last_days'] }), { tags: ['study'] }),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },

  // ===== 感染治療 =====
  {
    id: 'herbal_cure',
    stages: ['juvenile', 'adolescent', 'adult'],
    weight: 4,
    condition: s => s.traits.some(t => t.id === 'infected'),
    narratives: ['傷口的感染越來越嚴重，每一步都在抽痛。你聞到附近有一股苦澀的草藥氣味……'],
    fact: '許多現代動物會食用特定植物或泥土來處理寄生蟲和消化問題，這種行為稱為「動物自我藥療」。',
    mainActions: [
      A('eat_bitter_herb', '吃下苦澀的草藥', '良藥苦口', 'int', 9, [3, 3],
        R('苦得要命，但幾天後傷口的腫脹消退了。感染痊癒了！', 10, 0, 0, { traitRemove: 'infected' }),
        R('你吃錯了草，拉了好幾天肚子。', -5, -5, -5)),
      A('wash_wound', '用清水沖洗傷口', '保持清潔', 'int', 11, [2, 5],
        R('乾淨的溪水沖走了膿血，傷口開始癒合。感染痊癒了！', 5, 0, 5, { traitRemove: 'infected' }),
        R('水不夠乾淨，傷口更痛了。', -5)),
      A('mud_poultice', '在礦物泥裡打滾', '泥巴能吸走毒素？', 'str', 9, [3, 3],
        R('礦物泥封住了傷口。感染痊癒了！', 5, 0, 0, { traitRemove: 'infected' }),
        R('泥巴裡全是蟲。', -3)),
    ],
    subActions: [SUB_REST, SUB_DRINK],
  },
];
